// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/vaynedu/ddd_order_example/internal/application/service"
	"github.com/vaynedu/ddd_order_example/internal/domain/order"
	"github.com/vaynedu/ddd_order_example/internal/infrastructure/repository"
	"github.com/vaynedu/ddd_order_example/internal/interface/handler"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeOrderHandler 依赖注入入口
func InitializeOrderHandler(db *gorm.DB) (*handler.OrderHandler, error) {
	orderRepository := NewOrderRepository(db)
	orderService := NewOrderService(orderRepository)
	orderHandler := NewOrderHandler(orderService)
	return orderHandler, nil
}

// wire.go:

// NewOrderRepository - 初始化仓储
func NewOrderRepository(db *gorm.DB) order.OrderRepository {
	return repository.NewOrderRepository(db)
}

// NewOrderService 初始化应用服务
func NewOrderService(repo order.OrderRepository) *service.OrderService {
	return service.NewOrderService(repo)
}

// NewOrderHandler 初始化处理器
func NewOrderHandler(orderService *service.OrderService) *handler.OrderHandler {
	return handler.NewOrderHandler(orderService)
}
