// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/domain_payment_core/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/domain_payment_core/service.go -destination=internal/infrastructure/mocks/payment_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
